version: 2
jobs:
  build-odc:
    machine: true
    steps:
      - checkout
      - run: 
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            cd odc-jupyter-image/
            ls -la
            git submodule update --init --recursive
            cd odc-sandbox-notebooks
            ls -la
            cd ..
            docker build -t crcsi/odc-juypter-image:$CIRCLE_BRANCH-$CIRCLE_SHA1 .
            docker push crcsi/odc-juypter-image:$CIRCLE_BRANCH-$CIRCLE_SHA1 

  build-dask:
    machine: true
    steps:
      - checkout
      - run: 
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            cd dask/
            docker build -t crcsi/dask:$CIRCLE_SHA1 -t crcsi/dask:latest .
            docker push crcsi/dask:$CIRCLE_SHA1 
            docker push crcsi/dask:latest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-odc
