version: 2
jobs:
  build-odc:
    machine: true
    steps:
      - checkout
      - run: 
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            cd ga-sandbox-jupyter-image/
            #ls -la
            #git submodule update --init --recursive
            #cd dea-sandbox-notebooks
            #ls -la
            #cd ..
            docker build -t crcsi/ga-sandbox-jupyter-image:latest .
            docker push crcsi/ga-sandbox-jupyter-image:latest 

  build-dask:
    machine: true
    steps:
      - checkout
      - run: 
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            cd dask/
            docker build -t crcsi/dask:$CIRCLE_SHA1 -t crcsi/dask:latest .
            docker push crcsi/dask:$CIRCLE_SHA1 
            docker push crcsi/dask:latest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-odc
